spring:
#configuring connection to postgre db on localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/step_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#logpass for browser basic authentication
  security:
    user:
      name: step
      password: 123456
