spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/step_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  security:
    user:
      name: step
      password: 123456
